# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Eric Binard
email: "eric@binard.pro"
form: "xdobqbbk"
description: >
  Software architect/developer, looking to share my programming journey, as well as keep an organized cv in one place.
about_me: >
  I've always been passionate by computers.
  When I've finished my bachelor, I was sure that I've made the right choice.
  In my career, I've been working with so many inspiring people as other developers, architects and functional analysts. All these collaborations built my technicals and human skills.
  Finally, my main goal in programming is to build maintainable, robust, flexible and automatically tested softwares 🤓.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eric.binard.pro/" # the base hostname & protocol for your site, e.g. http://example.com
linked_in_link: "https://www.linkedin.com/in/eric-binard"
github_link: "https://www.github.com/chesteric31"
twitter_username: ""
google_analytics_id: 'UA-117297510-1'
select_options: clear-filters HTML5 CSS3 SCSS javaScript jQuery materialize charts.js React jekyll Ruby-on-Rails Sinatra front-end back-end finished current
sass:
  sass_dir: assets/css/main.css
  style: :nested

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
